---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-case-conflict
      - id: end-of-file-fixer
        exclude: ^.flox/env/manifest.lock$
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: local
    hooks:
      - id: just
        name: just
        entry: just
        args: ["pre-commit"]
        language: system
        pass_filenames: false
