---
name: Example / axum

"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    name: Detect changes
    runs-on: warp-ubuntu-latest-x64-2x
    permissions:
      contents: read
    outputs:
      any_changed: ${{ steps.detect-changes.outputs.any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: Get changed files
        id: detect-changes
        uses: tj-actions/changed-files@48d8f15b2aaa3d255ca5af3eba4870f807ce6b3c # v45
        with:
          files: |
            .github/workflows/axum.yml
            crates/**/*
            examples/axum-postgres/**/*

  format:
    name: Check Rust style
    runs-on: warp-ubuntu-latest-x64-2x
    permissions:
      contents: read
    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
    defaults:
      run:
        working-directory: examples/axum-postgres
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: Check formatting
        run: cargo fmt --all --check

  lint:
    name: Lint Rust code
    runs-on: warp-ubuntu-latest-x64-2x
    permissions:
      contents: read
    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
    defaults:
      run:
        working-directory: examples/axum-postgres
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: Lint with Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: Run integration tests
    runs-on: warp-ubuntu-latest-x64-2x
    permissions:
      contents: read
    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: Build and test with Docker Compose
        working-directory: examples/axum-postgres
        run: |
          docker compose up --build --abort-on-container-exit --exit-code-from tests
          docker compose down -v
